import mobiles.Android;
import mobiles.IPhone;
import mobiles.Mobile;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }
//
//    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//    }

    public static void main(String[] args) {
        Mobile plainMobile = new Mobile();
        Mobile iPhone = new IPhone();
        Mobile android = new Android();

        plainMobile.call("sample message");
        iPhone.call("sample message");
        android.call("sample message");
    }
}
